paths:
  "/drafts/content/:id/annotations":
    table: draft_annotations
    columns:
      uuid: ":id"
      last_modified: "@._timestamp"
      publish_ref: "@.x-request-id"
      body: "$"
    primaryKey: uuid
    hasConflictDetection: true
  "/published/content/:id/annotations":
    table: published_annotations
    columns:
      uuid: ":id"
      last_modified: "@._timestamp"
      publish_ref: "@.x-request-id"
      body: "$"
    primaryKey: uuid
    hasConflictDetection: false
  "/drafts/content/:id":
    table: draft_content
    columns:
      uuid: ":id"
      last_modified: "@._timestamp"
      draft_ref: "@.x-request-id"
      origin_system: "@.x-origin-system-id"
      body: "$"
    primaryKey: uuid
    hasConflictDetection: false
    response:
      headers:
        "X-Origin-System-Id": origin_system
        "Write-Request-Id": draft_ref
        "Last-Modified-RFC3339": last_modified
