paths:
  "/drafts/content/:id/annotations":
    table: draft_annotations
    columns:
      uuid: ":id"
      last_modified: "@.timestamp"
      publish_ref: "@.publishRef"
      body: "$"
    primaryKey: uuid
    hasConflictDetection: true
  "/published/content/:id/annotations":
    table: published_annotations
    columns:
      uuid: ":id"
      last_modified: "@.timestamp"
      publish_ref: "@.publishRef"
      body: "$"
    primaryKey: uuid
    hasConflictDetection: false
  "/drafts/content/:id":
    table: draft_content
    columns:
      uuid: ":id"
      last_modified: "@.timestamp"
      draft_ref: "@.x-request-id"
      origin_system: "@.x-origin-system-id"
      body: "$"
    primaryKey: uuid
    hasConflictDetection: false
