# Values used for the deployed application.
replicaCount: 2

service:
  name: generic-rw-aurora

encrypted:
  db.connection.string: AgCRvl60jz+SMECC/ssGM0DGiia3eiS2IfqH9b3Dx694+VmPLzsBexcOjo/cXNOfmpAeT1TVPzRfCtGLi3axpp3rDn1kxSSz/Kj2/8ufuAww3b3P1Tsix5spC9fVALwHN6lot9fh9VDswqJ112T2idr5GFAuuT+Xx/pUURgpBunRAZfpNEbSH3CjNSbCHPrbvfcTS1mU7u38JJOxCMnB7i2jl/tuGA4HRZBCXspw5w1y9o77fp74FTedpkIom0qKLWb+muMUTwFghNm0ZWmubxoHdmqTZqQv747NP/bl/adEsdZh6OMllDJ5Njl/47JqoOKhoKjbDlmA1ZE5Zs2G43BsWPMWH1OC0Uix6A54a0pxR8rXGpuoWxwJyCR2kqopWT0QLUr6yiTXw0EwnbmQUcw44ncS8zIlKO3XYX5vrYOMaVpcv37cbJWWOf8tRv0vuzwhyMLwLJ+lPInKcnLpGUr+yq3epDQIwI2ZdIu8X34TYmGoOXEZjXXFNnUGHhm89E6XnMKWaMHXJtpngMhYrdk/Q9xkivirVjFeCYrICaE1qd0DjU1PSIDP+FCF0GQZeOuSeptUuKRih7MEKSWz3T/NN7p7VYXP+gwxkxVEbQyMc+v1BxVZ7rr22TFek+GB3Nf23H2mQr+gwQw4n37J25kmgFDuKCCqsySR2mbLcaPVFBF1VKrXzjAJgrix+2H6e909wqDnrQWNGKY3DDr/6vnmaVQdJQKQt2o/Ac0j7yIjTjcZxW8UeqmS4uI1qggBujWTUxAiNjc+t6n3pPXydB/CqFhaiOEqLkr8KGiGFGSTGw==
