# Values used for the deployed application.
replicaCount: 2

service:
  name: generic-rw-aurora

encrypted:
  db.connection.string: AgCHWb4bcUiQRbEV8FYfSN5jxWTjjDMvId1bKX4ukiTHtX3BkPKjeIttjfYqzgMYKwGHUwpamsyajirG5C/9FPf1CvVCdHPV52t8N6w8zUGXyU2cmrn2JV8/J02mzt1mDr6DwLnOCR+a2DtYbyiHDL0yD3Fj3zKONEUb2pc8M5TkPynAP11xZ3N2PCjd65DSK0n0K5vkKZv2UZe66SJUJ3E4TstjUSvDUN/OLtYZ3+UWA3YDcRvBPBReYEoP2+I2rdPn5TxCN2aBj8ibZhSYY756fOYhHhGMCyY6RwC4HWN7GMa9Hk8ulWjUNice5o9cBSqmgDQ+Of9CQT4fbtEe4rn1stbS5VhIGpEtr875GZeNj4AUaTGlNxeQz54EoFTXdZbwiptUTGFBC44bJ9aiQ0vLkElg6lsPoejT+ymsr3erhvB4foYUV1Aj/GKZtwBzhqzIQ2Use+RTDRPJ772IahM4Eqj9DjIh+3saYe7AmXE1Sp2s/3Iy8mRQ2+hpzUAumyuD9/C0We6aGeZAgRHrIc8i9gHqcJoiCG5lCHE63GFsxkaR0nwabsONpe+jrP3Guizid8PrMXSjSWkqfcRjC2jomEYMwr2hS7JMcJnudirdazxccnsL8aDwGg13xkEgOZm7jXa9+a0Va13mgBqxR045GV9zTXwK+6qz+aNOfvFoUACs+XOuo+BfSFffb7gdcBNcRgxedZo8X5MMUJLKBkb0ywy7hfJJz83Mx0KoYUaRVIYXoSuUG1tD0eHMzxjlNBkW0yZvz45oz4bOCa7CUBM8Pj/dSptGkflPk4gv8A==
