# Values used for the deployed application.
eksCluster: true

replicaCount: 2

service:
  name: generic-rw-aurora

encrypted:
  db.connection.string: AgCKHbs+VUc7zWagn7Jhzmd4uCu5NZaz9fjB4Jf2pc2Px0zTLPjNa6/uqgDUIq13UglPRR/ylbY+0nwS1aa6AiPOBDUV1IiwdUaaF72SyYbUP33dsTapZvLVLafJJVExGMzmfpWlJQVzAd6GCgjTk9ATz/hjgjqSXhzRhh5/GPgyQqd65KZBG3TcJqMCxQ2tL0HrvMl4OW2cQs0mT9ZUeG86nIS4JQRH9jtWfG5V+C1PiNqsdtcliazdn695k3ii4Ri2Tz8FnRqIxS7OGgQ1d9VDLAtt+PBaaqT3YaiiTDQx0dNLD1P0Nn0r6xw6pcOBzUWLxxlR/BflhmX8LouaCQaEZVWQZH6565dpz5kxvigMh0YyW5bfVjyLbgXyDLgVRld+HZ9blXzXJvdd18Q4Abpb6b7CYyiLUBUqQyWGzZLCXKno8+GBbmaITdBeBjYHkbRKTpM15jPnglVb++7IIkbm1IbJHlPsej5ODZk8kWHQbMvTVk8xJ024EXE6u6dViKjLRcrr2AY28+Bai990NdpIpk0qsvlsyMfCx1acQCa/5b+ABgirwzWoxyiYl3tuXRld0E/3DXGO04oRpj0QPaTjYlYLzyZ4tk/OSY+MJ4z/xzez9NvU+96mPnVzGKxthe1J2KtnW2j/te1ad6LMpDYlGFabk7J1baeOw8eQovy7GmWcQ2xoiCw3a3rZyvopSbjEVLl7D+18Ojat8wUwwUbKzlgyX0hxzpSXgQS9dbkNxMShdBCbgQY1MkJkH+r/9+2borx59vsyRW2rNTRQzAQKR2yZaQcGf34jAwquurP22RfVIADPN8pqn3UAfi7Mk1iC8DG8tTRYhx2NkJK1PH7AyJDNr7g5W2tTsSgq
