# Values used for the deployed application.
replicaCount: 2

service:
  name: generic-rw-aurora

encrypted:
  db.connection.string: AgCR2NhzA1lRORNKPLx6rnaMbbl7Mi3G8Ypm7CYMzZcHepg/a1tbSFWNz5ics2c8jimodvLO7ikfSfe9OyVnXoNcexy6dRiw2q755skZxtzyyf6QIMdrUWAlMiD5FjO6QoRkXvyjkpup1uZRvhIfJIMDJDbgPvD9xfAIJQUkE9knsbWbUwyBjtNHMS5kQje3YwQW5qp8G4I9stsrML86CWK++4sababeVuKjAUSZl0cKr991FFNxBmHwGIwyMM5yk/udEYodpQcCM6as28F1Vt3+dyv0JtZFosd+ibkeKqEiIyqggD93J+3KnK7FXny0ZUatN0qDAT6EdFecW2QL53YlIcQ39N6yP2/Zz9XHEM3WzZTBDulAXesF8SSnO4buIWiQtyZr6jCcOmWN/8+afwNDZKqMtOZ6xtzGDVzms9J0iWh0eiwvePC8hBZPYDoysPdLh//5mt0u1+z75Hf/7lCf708FtG6VWgOzj5WwDtq72RkljXPwVst6Fa0Rwt9YPRyIXo/yDTF79XU7tGgiJAa0pVAJJDMChg3wwX3ZiMhmDAXWRKNUkuFY77shb+gzIAMW4ZwOy+mv+y7VbdTLC6RVkpGZltfOytbMytYZ0Cfkjj3ugnTW3WCHDcNx4hxaBAeBuODRSwMoH+vffUkUWFpSbCiaim38sgQikbNH+v9N/HYMViOmARXO0oGgZHF7ffZ5E0hNjtzZkn5CpIAeJtJyJ/32MVGbjQFGOrEaNBvkW9MVTc8PKrEx1g2ZbJj3m33dubMYe+WpuiJ374GdoSaE24YgXTPyesJqiNrvsMQ+/A==
