# Values used for the deployed application.
replicaCount: 2

service:
  name: generic-rw-aurora

encrypted:
  db.connection.string: AgBnOglA0R0mCWDlXMdqHoNcEMSRzRkhxyAFtqV0+U2O3z3YGoYmZkDUsHpDK2TxMzrfxadzMtLuGkQN+dGk1prZyN063Gs0dnOIhyHENC2mf6nrpqoeaV59kRdpe1GOIbBOQ7inmEIQj8crXCxSMj2nzmO1+l+nETX1jL8w0a+Ed9nQNc8xDVASR2Bx1f+jsVvKVX+hvRStoOPcTHTWDLDhWgSFgWZ8P9fYz9HGCUs16JfkXY6nrSIVF+54ga8qPxMBvxstLAqYSymlrVaPyUftoN8DpEos1YEbexCeqhSv2No/W0Fvw2xHYdIMfIafUQdzgVhlCNoh6WLfchTxP+3lljhvLJsqHqRn/mOINmL+xOUkMvPA6fT9SRkGAGZV7eM+JbHk/b5VRyprfJl2i+NP88Lcq2TJT0MqXv4yA3R/lF7bY1bMBQgguBjQTN+/SKqqDlWF8w0YOZHumV0764xfVuCA8/ZwY4LcZB6Z+iFtWFslJNUSpK3VEeqs7emfQHOPGur+s2JciY/J6gt0lL0x3vFEmCIEOfMkEZ/yNVKlpI8GkvbA3DSvDZITy5Ssg7McQGHjH45LK4UBWctKVZJaQwxkMM6rRbHX8uhWkghsece1e4gPqh4ZNdKP7+OZpvCf35bQpUghbt8WDQpV4Q/5crJTp1CoRgsg6taI9FBx1KQcapCaJMVyIs2IRZMmLPygsismRNnO994XavEunhLNdyVYoJgy9Pdmsg99w4VgRu/AbZchq949rywFlCqk2njBX7UsKGN8B4pqkfrulir+kZpEnndNUGgIZxzy3w==
